### ISSUE TITLE
Use api directly to get current path(list)

### ISSUE THREAD

**Issue by karlch** [jcjgraf/BatchMark#1]
Instead of using the library to get the current path(list), we could just use the available api functions directly, i.e.
```
    start_paths = api.pathlist()
    current_path = api.current_path()
    start_index = start_paths.index(current_path)
```

This has a few advantages:
- Does not use interna of the library that are subject to change.
- Allows using this plugin in all modes, not only in library mode. We can even switch modes during selection, as long as we don't change the actual pathlist.

**Comment by jcjgraf** [comment]
Haha, how could I have overlook the first few function of the api, they do excactly what was looking for :laughing: 

Even though my prior implementation was working in all modes (not just library), an API is here to use it :smirk: 

Fixed in #4
