### ISSUE TITLE
Add command + keybinding to toggle batchselection

### ISSUE THREAD

**Issue by karlch** [jcjgraf/BatchMark#2]
In addition to the available `:batchmarkstart` and `:batchmarkend`, it would be great to have the option to just toggle the selection, i.e. `:batchmarktoggle`. Personally I would split the command base and suffix with a `-` for readability, i.e. `:batchmark-start`, `:batchmark-end` and `:batchmark-toggle`, but this is totally up to you of course.

We could then bind `:batchmark-toggle` to a key, e.g. `V` (capital v).

What do you think?

Concerning the implementation, it might make sense to introduce a class to take care of the state (active, inactive) as well as storing the start paths/index.

**Comment by jcjgraf** [comment]
I have followed your suggestions and splitte the commands and I have also added a `batchmark-toggle` command too. 

But why would you add key binding for the toggle? I mean the matchmark start and end are much more often used. Personally, I am also not really a fan of plugins which add arbitrary keybindings; this just leads to binding clashes and confusion. I would rather add a note to the README about sensible bindings. However, if this plugins gets merged into vimiv, then it is another story...

**Comment by karlch** [comment]
Ah, sorry, I was unclear on what I meant with `:batchmark-toggle`, my bad! The idea was to have a command that:
- calls `:batchmark-start` if we **are not** currently in a batch marking state
- calls `:batchmark-end` if we **are** currently in a batch marking state

Like this one just has to use one command for both, and therefore the keybinding would also make much more sense as we can start and stop the selection with the same binding. I do agree with your point of plugins defining arbitrary keybindings, let's see where this goes first :blush:

**Comment by jcjgraf** [comment]
Oh yes, this makes much more sense! I have added that :relaxed:

**Comment by karlch** [comment]
Awesome, thanks!
