### ISSUE TITLE
Visual indication of batch selection

### ISSUE THREAD

**Issue by karlch** [jcjgraf/BatchMark#3]
The first simple indicator could be a statusbar module that displays some keyword when batch selection is active and nothing when it is not. One could then put this in front of the mode indicator along with the other mark-related indicators.

It would of course be super-nice if all the marking took place on the fly, but I have no clue if this is possible in the current state of vimiv :laughing: I will think about it.

**Comment by jcjgraf** [comment]
As indicated, I have added a status bar module in #5
